' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.gdiag/plantuml-libs"
' loads the library
!include $LIB_BASE_LOCATION/bootstrap.puml
' include eventstorming stuff
include('eventstorming/bootstrap')
include('eventstorming/Element/Command')
include('eventstorming/Element/Process')
include('eventstorming/Element/Event')
include('eventstorming/Element/IntegrationEvent')
include('eventstorming/Element/Service')
include('eventstorming/Element/Query')
include('eventstorming/Element/Result')
include('eventstorming/Element/UserInterface')
include('eventstorming/Element/Comment')

' app

!procedure LoadAppState()
  Command("LoadAppState")
!endprocedure

!procedure AppStateChanged()
  IntegrationEvent("AppStateChanged")
!endprocedure

!procedure AppStateChangedProducer()
  Process("AppStateChangedProducer")
!endprocedure

' filter

!procedure ChangeFilter()
  Command("ChangeFilter")
!endprocedure

' state

!procedure PersistState()
    IntegrationEvent("PersistState")
!endprocedure

!procedure PersistState()
    Command("PersistState")
!endprocedure

!procedure StateChanged()
    Event("StateChanged")
!endprocedure

!procedure StateFacade()
    Service("StateFacade")
!endprocedure

!procedure StateRepository()
    Service("StateRepository")
!endprocedure

!procedure LoadState()
    Query("LoadState")
!endprocedure

' state

!procedure AddTodo()
  Command("AddTodo")
!endprocedure

!procedure EditTodo()
  Command("EditTodo")
!endprocedure

!procedure ToggleTodo()
  Command("ToggleTodo")
!endprocedure

!procedure RemoveTodo()
  Command("RemoveTodo")
!endprocedure

!procedure ToggleAllTodos()
  Command("ToggleAllTodos")
!endprocedure

!procedure RemoveCompletedTodos()
  Command("RemoveCompletedTodos")
!endprocedure

' views

!procedure UiApp()
  UserInterface("UiApp")
!endprocedure

!procedure UiFilterList()
  UserInterface("UiFilterList")
!endprocedure

!procedure UiHeader()
  UserInterface("UiHeader")
!endprocedure

!procedure UiTodoItem()
  UserInterface("UiTodoItem")
!endprocedure

!procedure UiTodoList()
  UserInterface("UiTodoList")
!endprocedure

!procedure UiFooter()
  UserInterface("UiFooter")
!endprocedure

!procedure UiMain()
  UserInterface("UiMain")
!endprocedure
